Add about component
4klabs/portfolio pull request #14
Opened 2022-06-02 01:32 UTC by VictorCosta7

Resolves #10

Criação do componente "About".

2022-06-02 02:11 UTC, mateus4k requested changes
Parabéns pelo código, Victor!

Dá uma olhada nos comentários que deixei 😉

2022-06-02 02:11 UTC, mateus4k commented on client/src/App.vue
> +  font-family: 'Rajdhani', sans-serif;
Pode incluir prints da fonte? 👀

2022-06-02 02:11 UTC, mateus4k commented on client/src/App.vue
> +  font-family: 'Patrick Hand', cursive;
Pq a fonte sentada aqui é diferente da importada anteriormente?

2022-06-02 02:11 UTC, mateus4k commented on client/src/components/AboutComponent.vue
> +        <p>Oi! Eu sou Victor Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima ut tenetur, provident nemo sapiente pariatur ad in delectus! <br>
Esses textos devem vir de uma variável armazenada neste componente, assim vai ser possível alterarmos esses valores dinamicamente no futuro 🙂 

Ex.:
```js
<h1>{{ title }}</h1>
<p>{{ text }}</p>
```

2022-06-02 02:11 UTC, mateus4k commented on client/src/components/AboutComponent.vue
> +  background-image: url(../assets/victor_image.jpg);
A imagem aqui virá de uma URL, não de um arquivo local no projeto 😬 

Quando integrarmos com a API, esse tipo de coisa vai nos permitir trocar a imagem/texto do front remotamente 🙂

2022-06-02 02:23 UTC, VictorCosta7 commented on README.md
> +<img class="victor_image" src="../assets/victor_image1.jpg" onmouseover="this.src='../assets/victor_image1.jpg'"
Tentei alterar a imagem quando o mouse fica sob ela

2022-06-02 02:25 UTC, mateus4k commented on README.md
> +<img class="victor_image" src="../assets/victor_image1.jpg" onmouseover="this.src='../assets/victor_image1.jpg'"
É pq isso está no arquivo readme :grimacing: 

Deve ter sido por engano

2022-06-02 13:18 UTC, mateus4k commented on client/src/components/AboutComponent.vue
> +        <p>Oi! Eu sou Victor Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima ut tenetur, provident nemo sapiente pariatur ad in delectus! <br>
Doc: https://v2.vuejs.org/v2/guide/#Declarative-Rendering

2022-06-02 13:23 UTC, mateus4k commented on client/src/components/AboutComponent.vue
> +  background-image: url(../assets/victor_image.jpg);
Outro ponto é que nesse caso de imagem o mais comum é utilizar a tag `img`

Exemplo de como precisamos fazer: https://stackoverflow.com/a/43573618/9831377

2022-06-02 15:29 UTC, VictorCosta7 commented on README.md
> +<img class="victor_image" src="../assets/victor_image1.jpg" onmouseover="this.src='../assets/victor_image1.jpg'"
sim, vou procurar algum efeito legal

2022-06-02 15:32 UTC, VictorCosta7 commented on README.md
> +<img class="victor_image" src="../assets/victor_image1.jpg" onmouseover="this.src='../assets/victor_image1.jpg'"
> É pq isso está no arquivo readme 😬
> 
> Deve ter sido por engano

Queria salvar o codigo pra o usar depois e acabei esquecendo la

2022-06-02 15:35 UTC, VictorCosta7 commented on client/public/index.html
> +
não sei, ajustando...

2022-06-02 15:37 UTC, VictorCosta7 commented on client/src/App.vue
> +  font-family: 'Rajdhani', sans-serif;
onde devo incluir os prints?

2022-06-02 15:45 UTC, VictorCosta7 commented on client/src/App.vue
> +  font-family: 'Rajdhani', sans-serif;
![font_rajdhani](https://user-images.githubusercontent.com/95293703/171668756-bdffc5c3-46b0-411b-89c1-87884762b08e.png)

2022-06-02 15:50 UTC, VictorCosta7 commented on README.md
> +<img class="victor_image" src="../assets/victor_image1.jpg" onmouseover="this.src='../assets/victor_image1.jpg'"
Vou pesquisar e tentar fazer

2022-06-07 21:19 UTC, mateus4k commented on README.md
> +<img class="victor_image" src="../assets/victor_image1.jpg" onmouseover="this.src='../assets/victor_image1.jpg'"
Dando unresolve nessa thread pra gente não esquecer de remover esse trecho. Quando vc commitar e subir a solução aí fechamos a thread :slightly_smiling_face:

2022-06-12 19:50 UTC, mateus4k approved these changes

2022-06-12 19:54 UTC, merged